import { useState, useMemo } from "react";
import { motion } from "framer-motion";
import { Search, Download, ChevronLeft, ChevronRight, Eye, EyeOff, Lock, FileSpreadsheet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import type { ParsedTransaction } from "@/lib/pdfParser";
import { type PlanId, hasFeature, PLANS } from "@/lib/plans";

const CATEGORY_COLORS: Record<string, string> = {
  "Airtime/Data": "bg-chart-red/15 text-chart-red",
  Utilities: "bg-chart-blue/15 text-chart-blue",
  "Bank Payment": "bg-chart-purple/15 text-chart-purple",
  Food: "bg-chart-green/15 text-chart-green",
  "Cash Withdrawal": "bg-chart-yellow/15 text-chart-yellow",
  "Forex/Exchange": "bg-chart-blue/15 text-chart-blue",
  "Interest Earned": "bg-chart-green/15 text-chart-green",
  Remittance: "bg-chart-purple/15 text-chart-purple",
  "Transfer Received": "bg-chart-green/15 text-chart-green",
  Other: "bg-muted/15 text-muted",
};

const PAGE_SIZE = 25;

interface TransactionTableProps {
  transactions: ParsedTransaction[];
  plan?: PlanId;
}

const TransactionTable = ({ transactions, plan = "anonymous" }: TransactionTableProps) => {
  const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("All");
  const [page, setPage] = useState(1);
  const [showExtraCols, setShowExtraCols] = useState(false);

  const categories = useMemo(() => ["All", ...new Set(transactions.map((t) => t.category))], [transactions]);

  const filtered = useMemo(() => {
    return transactions.filter((t) => {
      const matchSearch = t.description.toLowerCase().includes(search.toLowerCase()) ||
        t.from?.toLowerCase().includes(search.toLowerCase()) ||
        t.to?.toLowerCase().includes(search.toLowerCase());
      const matchCategory = categoryFilter === "All" || t.category === categoryFilter;
      return matchSearch && matchCategory;
    });
  }, [transactions, search, categoryFilter]);

  const totalPages = Math.ceil(filtered.length / PAGE_SIZE);
  const paginated = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  // Reset page when filter changes
  useMemo(() => setPage(1), [search, categoryFilter]);

  const canCsvExport = hasFeature(plan, "csvExport");
  const canExcelExport = hasFeature(plan, "excelExport");
  const isAnonymous = plan === "anonymous";

  const exportCSV = () => {
    const header = "Date,Time,Description,Transaction ID,From,To,Amount(UGX),Fees(UGX),Taxes(UGX),Balance(UGX),Type,Category\n";
    const watermarkRow = isAnonymous
      ? '"Generated by MoMoSense — momosense.lovable.app — Sign up free to remove watermark","","","","","","","","","","",""\n'
      : "";
    const rows = filtered
      .map((t) =>
        `${t.date},"${t.time}","${t.description}","${t.transactionId}","${t.from}","${t.to}",${t.amount},${t.fees},${t.taxes},${t.balance},${t.type},${t.category}`
      )
      .join("\n");
    const blob = new Blob([watermarkRow + header + rows], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `momosense-statement-${new Date().toISOString().split("T")[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.7 }}
      className="stat-card"
    >
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
        <div>
          <h3 className="font-heading font-semibold text-foreground">All Transactions</h3>
          <p className="text-xs text-muted mt-1">{filtered.length} transactions found</p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted" />
            <input
              type="text"
              placeholder="Search..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-9 pr-4 py-2 bg-background border border-border rounded-[10px] text-sm focus:outline-none focus:ring-2 focus:ring-primary w-48"
            />
          </div>
          <select
            value={categoryFilter}
            onChange={(e) => setCategoryFilter(e.target.value)}
            className="bg-background border border-border rounded-[10px] px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
          >
            {categories.map((c) => (
              <option key={c} value={c}>{c}</option>
            ))}
          </select>
          <Button
            variant="outline"
            size="sm"
            className="rounded-[10px] gap-2"
            onClick={() => setShowExtraCols(!showExtraCols)}
          >
            {showExtraCols ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
            {showExtraCols ? "Hide" : "Show"} Fees/Taxes
          </Button>
          {/* CSV Export */}
          {isAnonymous ? (
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <span className="inline-flex items-center gap-1 opacity-50 cursor-not-allowed">
                    <Lock className="w-3.5 h-3.5 text-muted-foreground" />
                    <Button variant="outline" size="sm" className="rounded-[10px] gap-2 pointer-events-none" tabIndex={-1}>
                      <Download className="w-4 h-4" />
                      Export CSV
                    </Button>
                  </span>
                </TooltipTrigger>
                <TooltipContent><p className="text-xs">Sign up free to export CSV</p></TooltipContent>
              </Tooltip>
            </TooltipProvider>
          ) : (
            <Button variant="outline" size="sm" className="rounded-[10px] gap-2" onClick={exportCSV}>
              <Download className="w-4 h-4" />
              Export CSV
            </Button>
          )}
          {/* Excel Export */}
          {canExcelExport ? (
            <Button variant="outline" size="sm" className="rounded-[10px] gap-2" onClick={() => { /* TODO: Excel export */ }}>
              <FileSpreadsheet className="w-4 h-4" />
              Export Excel
            </Button>
          ) : (
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <span className="inline-flex items-center gap-1 opacity-50 cursor-not-allowed">
                    <Lock className="w-3.5 h-3.5 text-muted-foreground" />
                    <Button variant="outline" size="sm" className="rounded-[10px] gap-2 pointer-events-none" tabIndex={-1}>
                      <FileSpreadsheet className="w-4 h-4" />
                      Export Excel
                    </Button>
                  </span>
                </TooltipTrigger>
                <TooltipContent><p className="text-xs">Available on Starter plan and above — UGX 15,000/month</p></TooltipContent>
              </Tooltip>
            </TooltipProvider>
          )}
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border">
              <th className="text-left py-3 px-2 text-xs font-medium text-muted">Date</th>
              <th className="text-left py-3 px-2 text-xs font-medium text-muted">Description</th>
              <th className="text-left py-3 px-2 text-xs font-medium text-muted">Type</th>
              <th className="text-right py-3 px-2 text-xs font-medium text-muted">Amount</th>
              {showExtraCols && (
                <>
                  <th className="text-right py-3 px-2 text-xs font-medium text-muted">Fees</th>
                  <th className="text-right py-3 px-2 text-xs font-medium text-muted">Taxes</th>
                  <th className="text-right py-3 px-2 text-xs font-medium text-muted">Balance</th>
                </>
              )}
              <th className="text-left py-3 px-2 text-xs font-medium text-muted">Category</th>
            </tr>
          </thead>
          <tbody>
            {paginated.map((t, i) => (
              <tr key={i} className={`border-b border-border last:border-0 ${i % 2 === 1 ? "bg-background" : ""}`}>
                <td className="py-3 px-2 font-mono text-xs whitespace-nowrap">{t.date}</td>
                <td className="py-3 px-2 max-w-[200px] truncate" title={t.description}>{t.description}</td>
                <td className="py-3 px-2">
                  <span className={`text-xs font-medium ${t.type === "received" ? "text-chart-green" : "text-chart-red"}`}>
                    {t.type === "received" ? "Received" : "Sent"}
                  </span>
                </td>
                <td className={`py-3 px-2 text-right font-mono font-medium ${t.type === "received" ? "text-chart-green" : "text-chart-red"}`}>
                  {t.type === "received" ? "+" : "-"}UGX {t.amount.toLocaleString("en-UG")}
                </td>
                {showExtraCols && (
                  <>
                    <td className="py-3 px-2 text-right font-mono text-xs text-accent">
                      {t.fees > 0 ? `UGX ${t.fees.toLocaleString("en-UG")}` : "—"}
                    </td>
                    <td className="py-3 px-2 text-right font-mono text-xs text-muted">
                      {t.taxes > 0 ? `UGX ${t.taxes.toLocaleString("en-UG")}` : "—"}
                    </td>
                    <td className="py-3 px-2 text-right font-mono text-xs">
                      UGX {t.balance.toLocaleString("en-UG")}
                    </td>
                  </>
                )}
                <td className="py-3 px-2">
                  <span className={`category-pill ${CATEGORY_COLORS[t.category] || CATEGORY_COLORS.Other}`}>
                    {t.category}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-between mt-4 pt-4 border-t border-border">
          <p className="text-xs text-muted">
            Page {page} of {totalPages}
          </p>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              className="rounded-[10px]"
              disabled={page <= 1}
              onClick={() => setPage(page - 1)}
            >
              <ChevronLeft className="w-4 h-4" />
            </Button>
            {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
              const start = Math.max(1, Math.min(page - 2, totalPages - 4));
              const p = start + i;
              if (p > totalPages) return null;
              return (
                <Button
                  key={p}
                  variant={p === page ? "default" : "outline"}
                  size="sm"
                  className="rounded-[10px] w-8 h-8 p-0"
                  onClick={() => setPage(p)}
                >
                  {p}
                </Button>
              );
            })}
            <Button
              variant="outline"
              size="sm"
              className="rounded-[10px]"
              disabled={page >= totalPages}
              onClick={() => setPage(page + 1)}
            >
              <ChevronRight className="w-4 h-4" />
            </Button>
          </div>
        </div>
      )}
    </motion.div>
  );
};

export default TransactionTable;
